experiment_dir: "/mnt/towbin.data/shared/ngerber/20230927_LIPSI_20x_348_297_20C_20230927_165930_303/pad2/"

building_blocks: ["segmentation", "straightening"]

rerun_segmentation: [False]
rerun_straightening: [False]
rerun_volume_computation: [False]
rerun_classification: [False]
rerun_molt_detection: [False]
rerun_fluorescence_quantification: [False]

# segmentation parameters
segmentation_column: ['raw']
segmentation_method: ["edge_based"]
segmentation_channels: [[2]]
augment_contrast: [False]
pixelsize: [0.65]
sigma_canny: [1]

model_path: ["/home/spsalmon/towbintools/towbintools/deep_learning/unet_confocal/good_confocal.ckpt"]
tiler_config: [[(512, 512), (256, 256)]]
RGB: [True]
activation_layer: [null]
batch_size: [-1]


# straightening parameters
straightening_source: [['raw', 1]]
straightening_masks: ['analysis/ch3_seg']

# volume computation parameters
volume_computation_masks: ['analysis/ch1_seg_str']

# classification parameters
classification_source: ['analysis/ch1_seg_str']
classifier: ["./models/worm_type_classifier.json"]

# molt detection parameters
molt_detection_volume: ['ch1_seg_str_volume']
molt_detection_worm_type: ['ch1_seg_str_worm_type']

# fluo quantification parameters
fluorescence_quantification_source: [['raw', 0]]
fluorescence_quantification_masks: ['analysis/ch1_seg']
fluorescence_quantification_normalization: ['area']

# custom parameters
custom_script_path : [null]
custom_script_parameters : [null]

# sbatch parameters
sbatch_memory: 128G
sbatch_time: 0-12:00:00
sbatch_cpus: 32
sbatch_gpus: 0
