experiment_dir: "/mnt/external.data/TowbinLab/kstojanovski/20230217-Ti2_10x_rheb-RNAi_wBT160-182-186-190_25C_20230217_143551_140"

building_blocks: [ "segmentation", "segmentation", "straightening", "straightening", "straightening","straightening", "volume_computation", "volume_computation","volume_computation", "classification"]

rerun_segmentation: [False]
rerun_straightening: [False]
rerun_volume_computation: [False]
rerun_classification: [False]
rerun_molt_detection: [False]
rerun_fluorescence_quantification: [False]

# segmentation parameters
segmentation_column: ['raw']
segmentation_name_suffix: ["germline","pharynx"]
segmentation_method: [ "deep_learning", "ilastik"]
segmentation_channels: [[1],[0]]
augment_contrast: [False]

# edge-based segmentation parameters
pixelsize: [0.65]
sigma_canny: [1]

# deep learning segmentation parameters
model_path: ["/mnt/towbin.data/shared/bgusev/deep_learning/models/dark_germline_seg/epoch=46-step=2021.ckpt"]
tiler_config: [[[512, 512], [256, 256]]]
RGB: [True]
activation_layer: [null]
batch_size: [8]

# ilastik segmentation parameters
ilastik_project_path: ["/mnt/external.data/TowbinLab/kstojanovski/classifier_training/ilastikProjects/pharynx_str_noCPR.ilp"]
ilastik_result_channel: [0]

# straightening parameters
straightening_source: [['raw', [1]], ['analysis/ch2_seg_worm', null], ['analysis/ch2_seg_germline', null],['analysis/ch1_seg_pharynx', null]]
straightening_masks: ['analysis/ch2_seg_worm','analysis/ch2_seg_worm','analysis/ch2_seg_worm','analysis/ch2_seg_worm']

# volume computation parameters
volume_computation_masks: ['analysis/ch2_seg_worm_str', 'analysis/ch2_seg_germline_str','analysis/ch1_seg_pharynx_str']

# classification parameters
classification_source: ['analysis/ch2_seg_worm_str']
classifier: ["./models/worm_type_classifier.json"]

# molt detection parameters
molt_detection_volume: ['ch2_seg_worm_str_volume']
molt_detection_worm_type: ['ch2_seg_worm_str_worm_type']

# fluo quantification parameters
fluorescence_quantification_source: [['raw', 0]]
fluorescence_quantification_masks: ['analysis/ch1_seg']
fluorescence_quantification_normalization: ['area']

# custom parameters
custom_script_path : [null]
custom_script_parameters : [null]

# sbatch parameters
sbatch_memory: 128G
sbatch_time: 0-48:00:00
sbatch_cpus: 32
sbatch_gpus: 2