experiment_dir: "/mnt/external.data/TowbinLab/spsalmon/pipeline_test_folder/"

building_blocks: ["segmentation", "straightening", "straightening", "volume_computation", "classification", "molt_detection", "fluorescence_quantification"]

rerun_segmentation: [False]
rerun_straightening: [False]
rerun_volume_computation: [False]
rerun_classification: [False]
rerun_molt_detection: [False]
rerun_fluorescence_quantification: [False]

# segmentation parameters
segmentation_column: ['raw']
segmentation_method: ["edge_based"]
segmentation_channels: [[0]]
augment_contrast: [False]
pixelsize: [0.65]
segmentation_backbone: ["skimage"]
sigma_canny: [1]

# straightening parameters
straightening_source: [['analysis/ch1_seg', null], ['raw', 0]]
straightening_masks: ['analysis/ch1_seg']

# volume computation parameters
volume_computation_masks: ['analysis/ch1_seg_str']

# classification parameters
classification_source: ['analysis/ch1_seg_str']
classifier: ["./models/worm_type_classifier.json"]

# molt detection parameters
molt_detection_volume: ['ch1_seg_str_volume']
molt_detection_worm_type: ['ch1_seg_str_worm_type']

# fluo quantification parameters
fluorescence_quantification_source: [['raw', 0]]
fluorescence_quantification_masks: ['analysis/ch1_seg']
fluorescence_quantification_normalization: ['area']


# sbatch parameters
sbatch_memory: 128G
sbatch_time: 0-12:00:00
sbatch_cpus: 32
sbatch_gpus: 0
