experiment_dir: "/mnt/external.data/TowbinLab/spsalmon/pipeline_test_folder/"

building_blocks: ["segmentation", "segmentation", "straightening", "volume_computation", "worm_type_classification", "molt_detection"]

rerun_segmentation: [False]
rerun_straightening: [False]
rerun_volume_computation: [True]
rerun_worm_type_classification: [True]
rerun_molt_detection: [True]

# segmentation parameters
segmentation_column: [['raw']]
segmentation_method: ["edge_based"]
segmentation_channels: [[0], [1]]
augment_contrast: [False]
pixelsize: [0.65]
segmentation_backbone: ["skimage"]
sigma_canny: [1]

# straightening parameters
straightening_source: [['analysis/ch1_seg', null]]
straightening_masks: [['analysis/ch1_seg']]

worm_type_classifier: "./models/worm_type_classifier.json"

# sbatch parameters
sbatch_memory: 128G
sbatch_time: 0-12:00:00
sbatch_cpus: 32
sbatch_gpus: 0
